// Universal type for all property types
export type PropertyDetails = {
  id: number;
  ownerId: number;
  Type: string;
  city: string;
  AdressByAPI?: string;
  townSector: string;
  location: string;
  landmark?: string;
  palaceName?: string;
  BHK?: string;
  BedCount?: number;
  MinPrice: string;
  MaxPrice: string;
  adress?: string;
  address?: string;
  Offer?: string;
  security?: string;
  maintenance?: string;
  totalFlat?: number;
  totalPG?: number;
  totalRoom?: number;
  totalFloor?: string;
  waterSupply?: string;
  powerBackup?: string;
  noticePeriod?: string;
  furnishingType?: string;
  accomoType?: string;
  acType?: string;
  parking?: string[];
  preferTenants?: string[];
  petsAllowed?: boolean;
  genderPrefer?: string;
  flatType?: string;

  roomType?: string;
  PGType?: string;
  PGInside?: string[];
  PGOutside?: string[];
  roomInside?: string[];
  roomOutside?: string[];
  flatInside?: string[];
  flatOutside?: string[];
  careTaker?: string;
  manager?: string;
  listingShowNo?: string;
  RoomAvailable?: string;
  foodAvailable?: boolean;
  timeRestrict?: boolean;
  noofGuests?: number;
  isVerified: boolean;
  verificationPending: boolean;
  paymentDone: boolean;
  isVisible: boolean;
  isDraft: boolean;
  updatedByOwner: string;
  verifiedByAdminOrAgent: string;
  postPropertyByAdmin: boolean;
  images?: string[] | { [key: string]: string };
  kycDocuments?: string[];
  selfVerifiedImages?: string[];
  agentVerifiedImages?: string[];
  bedCount ?: number;
  Adress?: string;
  roominside?: string[];
  roomoutside?: string[];
  bedcount ?: number;
  preferredTenants?: string[];
    foodavailable?: boolean;

};

export type Owner = {
  id: number;
  username: string;
  email: string;
  mobile: string;
  isPhoneVerified: boolean;
  points: number;
  isKYCVerified: boolean;
  role: string;
};